### ISSUE TITLE
leaflet 1.8

### ISSUE THREAD

**Issue by ammd1313** [w8r/Leaflet.Path.Transform#92]
not worked with leaflet v1.8

**Comment by w8r** [comment]
Working on it

**Comment by ammd1313** [comment]
level :2 message :Uncaught TypeError: L.DomEvent.skipped is not a function,lineNumber :258,sourceID:file:///****/L.Path.Transform-src.js


that line is 
L.DomEvent.skipped({ type: 'click' });

**Comment by ammd1313** [comment]
leaflet removed fakestop and skipped in verion 1.8 @w8r

**Comment by ammd1313** [comment]
https://github.com/w8r/Leaflet.Path.Transform/pull/94

**Comment by ammd1313** [comment]
https://github.com/w8r/Leaflet.Path.Transform/pull/94

**Comment by plarner30** [comment]
@w8r [w8r](https://github.com/w8r) hey do you have any update on when the fix might be available? Many thanks

**Comment by w8r** [comment]
#94 should've fixed it

**Comment by plarner30** [comment]
@w8r sweet thanks, to confirm how will it work in terms of an npm version number? Does that still need tagging?

**Comment by w8r** [comment]
`leaflet-path-transform@1.8.0-beta.2` should be there within minutes. It works with leaflet@1.8
